//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int Id { get; set; }
        public int amount { get; set; }
        public int cost { get; set; }
        public int dishId_FK { get; set; }
        public int orderId_FK { get; set; }
        public int status { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderLineStatus OrderLineStatu { get; set; }
    }
}
